spring:
  application:
    name: gateway-server
server:
  port: 8098
zuul:
  routes:
    feign-server-2:
      path: /feign/**
      serviceId: feign-server-2

    hello-server:
      path: /hello/**
      serviceId: hello-server

    feign-server:
      path: /api-b/**
      serviceId: feign-service
  prefix: /api #所有请求公共前缀
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    hostname: zuul-service